export const TILES = {
  1: { num:1, color:'BLACK'},
  2: { num:2, color:'BLACK'},
  3: { num:3, color:'BLACK'},
  4: { num:4, color:'BLACK'},
  5: { num:5, color:'BLACK'},
  6: { num:6, color:'BLACK'},
  7: { num:7, color:'BLACK'},
  8: { num:8, color:'BLACK'},
  9: { num:9, color:'BLACK'},
  10: { num:10, color:'BLACK'},
  11: { num:11, color:'BLACK'},
  12: { num:12, color:'BLACK'},
  13: { num:13, color:'BLACK'},
  14: { num:1, color:'BLACK'},
  15: { num:2, color:'BLACK'},
  16: { num:3, color:'BLACK'},
  17: { num:4, color:'BLACK'},
  18: { num:5, color:'BLACK'},
  19: { num:6, color:'BLACK'},
  20: { num:7, color:'BLACK'},
  21: { num:8, color:'BLACK'},
  22: { num:9, color:'BLACK'},
  23: { num:10, color:'BLACK'},
  24: { num:11, color:'BLACK'},
  25: { num:12, color:'BLACK'},
  26: { num:13, color:'BLACK'},

  27: { num: 1, color: 'BLUE' },
  28: { num: 2, color: 'BLUE' },
  29: { num: 3, color: 'BLUE' },
  30: { num: 4, color: 'BLUE' },
  31: { num: 5, color: 'BLUE' },
  32: { num: 6, color: 'BLUE' },
  33: { num: 7, color: 'BLUE' },
  34: { num: 8, color: 'BLUE' },
  35: { num: 9, color: 'BLUE' },
  36: { num: 10, color: 'BLUE' },
  37: { num: 11, color: 'BLUE' },
  38: { num: 12, color: 'BLUE' },
  39: { num: 13, color: 'BLUE' },
  40: { num: 1, color: 'BLUE' },
  41: { num: 2, color: 'BLUE' },
  42: { num: 3, color: 'BLUE' },
  43: { num: 4, color: 'BLUE' },
  44: { num: 5, color: 'BLUE' },
  45: { num: 6, color: 'BLUE' },
  46: { num: 7, color: 'BLUE' },
  47: { num: 8, color: 'BLUE' },
  48: { num: 9, color: 'BLUE' },
  49: { num: 10, color: 'BLUE' },
  50: { num: 11, color: 'BLUE' },
  51: { num: 12, color: 'BLUE' },
  52: { num: 13, color: 'BLUE' },
}