export const TILES = {
  1: { num:1, color:'BLACK'},
  2: { num:2, color:'BLACK'},
  3: { num:3, color:'BLACK'},
  4: { num:4, color:'BLACK'},
  5: { num:5, color:'BLACK'},
  6: { num:6, color:'BLACK'},
  7: { num:7, color:'BLACK'},
  8: { num:8, color:'BLACK'},
  9: { num:9, color:'BLACK'},
  10: { num:10, color:'BLACK'},
  11: { num:11, color:'BLACK'},
  12: { num:12, color:'BLACK'},
  13: { num:13, color:'BLACK'},
  14: { num:1, color:'BLACK'},
  15: { num:2, color:'BLACK'},
  16: { num:3, color:'BLACK'},
  17: { num:4, color:'BLACK'},
  18: { num:5, color:'BLACK'},
  19: { num:6, color:'BLACK'},
  20: { num:7, color:'BLACK'},
  21: { num:8, color:'BLACK'},
  22: { num:9, color:'BLACK'},
  23: { num:10, color:'BLACK'},
  24: { num:11, color:'BLACK'},
  25: { num:12, color:'BLACK'},
  26: { num:13, color:'BLACK'},

  27: { num: 1, color: 'BLUE' },
  28: { num: 2, color: 'BLUE' },
  29: { num: 3, color: 'BLUE' },
  30: { num: 4, color: 'BLUE' },
  31: { num: 5, color: 'BLUE' },
  32: { num: 6, color: 'BLUE' },
  33: { num: 7, color: 'BLUE' },
  34: { num: 8, color: 'BLUE' },
  35: { num: 9, color: 'BLUE' },
  36: { num: 10, color: 'BLUE' },
  37: { num: 11, color: 'BLUE' },
  38: { num: 12, color: 'BLUE' },
  39: { num: 13, color: 'BLUE' },
  40: { num: 1, color: 'BLUE' },
  41: { num: 2, color: 'BLUE' },
  42: { num: 3, color: 'BLUE' },
  43: { num: 4, color: 'BLUE' },
  44: { num: 5, color: 'BLUE' },
  45: { num: 6, color: 'BLUE' },
  46: { num: 7, color: 'BLUE' },
  47: { num: 8, color: 'BLUE' },
  48: { num: 9, color: 'BLUE' },
  49: { num: 10, color: 'BLUE' },
  50: { num: 11, color: 'BLUE' },
  51: { num: 12, color: 'BLUE' },
  52: { num: 13, color: 'BLUE' },

  53: { num: 1, color: 'RED' },
  54: { num: 2, color: 'RED' },
  55: { num: 3, color: 'RED' },
  56: { num: 4, color: 'RED' },
  57: { num: 5, color: 'RED' },
  58: { num: 6, color: 'RED' },
  59: { num: 7, color: 'RED' },
  60: { num: 8, color: 'RED' },
  61: { num: 9, color: 'RED' },
  62: { num: 10, color: 'RED' },
  63: { num: 11, color: 'RED' },
  64: { num: 12, color: 'RED' },
  65: { num: 13, color: 'RED' },
  66: { num: 1, color: 'RED' },
  67: { num: 2, color: 'RED' },
  68: { num: 3, color: 'RED' },
  69: { num: 4, color: 'RED' },
  70: { num: 5, color: 'RED' },
  71: { num: 6, color: 'RED' },
  72: { num: 7, color: 'RED' },
  73: { num: 8, color: 'RED' },
  74: { num: 9, color: 'RED' },
  75: { num: 10, color: 'RED' },
  76: { num: 11, color: 'RED' },
  77: { num: 12, color: 'RED' },
  78: { num: 13, color: 'RED' },

  79: { num: 1, color: 'GREEN' },
  80: { num: 2, color: 'GREEN' },
  81: { num: 3, color: 'GREEN' },
  82: { num: 4, color: 'GREEN' },
  83: { num: 5, color: 'GREEN' },
  84: { num: 6, color: 'GREEN' },
  85: { num: 7, color: 'GREEN' },
  86: { num: 8, color: 'GREEN' },
  87: { num: 9, color: 'GREEN' },
  88: { num: 10, color: 'GREEN' },
  89: { num: 11, color: 'GREEN' },
  90: { num: 12, color: 'GREEN' },
  91: { num: 13, color: 'GREEN' },
  92: { num: 1, color: 'GREEN' },
  93: { num: 2, color: 'GREEN' },
  94: { num: 3, color: 'GREEN' },
  95: { num: 4, color: 'GREEN' },
  96: { num: 5, color: 'GREEN' },
  97: { num: 6, color: 'GREEN' },
  98: { num: 7, color: 'GREEN' },
  99: { num: 8, color: 'GREEN' },
  100: { num: 9, color: 'GREEN' },
  101: { num: 10, color: 'GREEN' },
  102: { num: 11, color: 'GREEN' },
  103: { num: 12, color: 'GREEN' },
  104: { num: 13, color: 'GREEN' },

  // JOKERS
  105: { num: 14, color: 'RED' },
  106: { num: 15, color: 'BLACK' }
}